apiVersion: apps/v1
kind: Deployment
metadata:
  name: aespa-deployment
spec:
  selector:
    matchLabels:
      app: aespa-service-app
  replicas: 1
  template:
    metadata:
      labels:
        app: aespa-service-app
    spec:
      containers:
        - name: aespa-service
          image: aespa-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8091
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: aespa-service
spec:
  type: NodePort
  selector:
    app: aespa-service-app
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30001